In [1]:
import numpy as np

In [2]:
a1 = np.array([(1,2,3), (6,4,5)])

In [3]:
a1.max(axis=0)

array([6, 4, 5])

In [4]:
a1.max(axis=1)

array([3, 6])

In [7]:
a1[0,1],a1[1,2]

(2, 5)

In [8]:
a1.sort(axis=1)

In [9]:
a1

array([[1, 2, 3],
       [4, 5, 6]])